# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claumon < Formula
  desc "Real-time Claude Code dashboard — monitors API usage, token costs, sessions, and memory files"
  homepage "https://github.com/fabioconcina/claumon"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fabioconcina/claumon/releases/download/v0.9.1/claumon-darwin-amd64.tar.gz"
      sha256 "b9048bfbcbe9807faa8d120531247017a61967a0d5805054ba469b3f4e1cbcc6"

      define_method(:install) do
        bin.install "claumon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fabioconcina/claumon/releases/download/v0.9.1/claumon-darwin-arm64.tar.gz"
      sha256 "b851be108a6e5e50c488ffdd72731addc72a428dd905332b5395feef079a854e"

      define_method(:install) do
        bin.install "claumon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fabioconcina/claumon/releases/download/v0.9.1/claumon-linux-amd64.tar.gz"
      sha256 "212da5d74b9d02a38d67deffe23254ec1130d5aa2c401f6a912d779f8be9f360"
      define_method(:install) do
        bin.install "claumon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fabioconcina/claumon/releases/download/v0.9.1/claumon-linux-arm64.tar.gz"
      sha256 "3b6704809dc025af617f2d5eae7af5f846b2587e0eda6e9b426d23a136e5edb5"
      define_method(:install) do
        bin.install "claumon"
      end
    end
  end
end
