# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claumon < Formula
  desc "Real-time Claude Code dashboard — monitors API usage, token costs, sessions, and memory files"
  homepage "https://github.com/fabioconcina/claumon"
  version "0.13.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fabioconcina/claumon/releases/download/v0.13.2/claumon-darwin-amd64.tar.gz"
      sha256 "1cc3c0b6f02e36231d26bf0917dff828c6c7449710c502761f9e0e6c39ae3d6b"

      define_method(:install) do
        bin.install "claumon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fabioconcina/claumon/releases/download/v0.13.2/claumon-darwin-arm64.tar.gz"
      sha256 "4b3bae0d660ed4e091d1db925f19320f992b35eb33c987a0ec1078cea6ac3893"

      define_method(:install) do
        bin.install "claumon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fabioconcina/claumon/releases/download/v0.13.2/claumon-linux-amd64.tar.gz"
      sha256 "bd3cac674e8c2fc46ce6fc3b8c8856ab51652aa47452a8ea04d5ce6e9c78b429"
      define_method(:install) do
        bin.install "claumon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fabioconcina/claumon/releases/download/v0.13.2/claumon-linux-arm64.tar.gz"
      sha256 "d9f400265ae1d6b72658e427459cad2acbcb569423a01a9f0cc5cd48ba2c2309"
      define_method(:install) do
        bin.install "claumon"
      end
    end
  end
end
